Add test case for missing operator
The ">" (greater than) and "<=" (less than or equal) are defined but
not implemented

    --- FAIL: TestParserExpressionWithGreaterThan (0.00s)
    	simpleParser_test.go:734:
    			Error Trace:	simpleParser_test.go:734
    			Error:      	Expected nil, but got: &errors.errorString{s:"Error: Invalid op type: >"}
    			Test:       	TestParserExpressionWithGreaterThan